# File generated by Flopy version 3.10.0.dev2 on 05/09/2025 at 15:27:49.
BEGIN attributes
  NAMES  FLOWRATE
  METHODS  LINEAREND
END attributes

BEGIN timeseries
       0.00000000    2000.00000000
     307.00000000    6000.00000000
     791.00000000    5000.00000000
    1000.00000000    9000.00000000
END timeseries

